sonar.projectKey=urxnium-angular
sonar.projectName=urxnium-angular
sonar.projectVersion=0.0.1 alpha
sonar.sources=projects/ng-urxnium
sonar.exclusions=projects/ng-urxnium/src/test.ts
sonar.sourceEncoding=UTF-8
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://10.244.209.25:9000/
